// Automatically generated by the res2go IDE plug-in.
package main

import (
	"github.com/ying32/govcl/vcl"
	"ifofa/ui"
)

func main() {
	//vcl.Application.SetScaled(true)
	//vcl.Application.SetTitle("iFofa")
	//vcl.Application.Initialize()
	//vcl.Application.SetMainFormOnTaskBar(true)
	//vcl.Application.CreateForm(&ui.Form1)
	//vcl.Application.CreateForm(&ui.Form2)
	//vcl.Application.CreateForm(&ui.Form3)
	//vcl.Application.CreateForm(&ui.Form4)
	vcl.RunApp(&ui.Form1, &ui.Form2, &ui.Form3, &ui.Form4)
}
