// Automatically generated by the res2go IDE plug-in.
package main

import (
    "github.com/ying32/govcl/vcl"
    "./code"
)

func main() {
    vcl.Application.SetScaled(true)
    vcl.Application.SetTitle("iFofa")
    vcl.Application.Initialize()
    vcl.Application.SetMainFormOnTaskBar(true)
    vcl.Application.CreateForm(&code.Form1)
    vcl.Application.CreateForm(&code.Form2)
    vcl.Application.CreateForm(&code.Form3)
    vcl.Application.CreateForm(&code.Form5)
    vcl.Application.Run()
}
